

-- passowrd pattern
-- Welcome1!<username>
-- Example volunteer: maya_green / Welcome1!maya_green
-- Example event leader: leader_hana / Welcome1!leader_hana
-- Example admin: admin_nora / Welcome1!admin_nora

INSERT INTO users (
    username, password_hash, full_name, email, contact_number, home_address,
    profile_image, environmental_interests, role, status
) VALUES
    ('maya_green', '$2b$12$1g7TC3BMY67mxWTtF6fYQuyVqHKq0z6672qp/c4zdOipltmT5f0bu', 'Maya Green', 'maya.green@example.com', '021-111-1201', '12 Rata St, Lincoln', 'maya_green.jpg', 'beach cleanups, recycling', 'volunteer', 'active'),
    ('liam_harper', '$2b$12$MTdUdi4OK4inVuHe..rkG.uN56xERdWEIwYMfAeoflzUj1NKLS/Ji', 'Liam Harper', 'liam.harper@example.com', '021-111-1202', '4 Kauri Ave, Rolleston', 'liam_harper.jpg', 'river restoration, waste sorting', 'volunteer', 'active'),
    ('sophia_ngata', '$2b$12$8BPa5WQvkEFVSnWuWdRNxujSks7luoCThwSe4xQYxS8/8/KkX4uii', 'Sophia Ngata', 'sophia.ngata@example.com', '021-111-1203', '88 Pohutukawa Rd, Christchurch', 'sophia_ngata.jpg', 'tree planting, wetland care', 'volunteer', 'active'),
    ('ethan_clarke', '$2b$12$6.wsf3iBqgeNZuDWL8Nx3.eGePbu/ue5y67vp.eNW.1/DxJYG6AhC', 'Ethan Clarke', 'ethan.clarke@example.com', '021-111-1204', '21 Tui Lane, Halswell', 'ethan_clarke.jpg', 'park cleanups, composting', 'volunteer', 'active'),
    ('ava_morrison', '$2b$12$MPDxKGnGIMZEKjaI6BWZ4OY903kG5zIPNOfvVUO/XBXdmBamYdulC', 'Ava Morrison', 'ava.morrison@example.com', '021-111-1205', '7 Bellbird Cres, Lincoln', 'ava_morrison.jpg', 'community gardens, recycling', 'volunteer', 'active'),
    ('noah_fraser', '$2b$12$oYaMg/s0E6uOkj3uJahZiuECKrO53DZs.PwhZdNHpIV3Ufw6F4lou', 'Noah Fraser', 'noah.fraser@example.com', '021-111-1206', '53 Fern Dr, Burnside', 'noah_fraser.jpg', 'beach cleanups, education', 'volunteer', 'active'),
    ('isla_walker', '$2b$12$9toJQ4iRSMWzSg9wM2UxFePyy9ag0CWPdGISWVeziaRX0HzLuPJNq', 'Isla Walker', 'isla.walker@example.com', '021-111-1207', '42 Totara Pl, Hornby', 'isla_walker.jpg', 'tree planting, wildlife protection', 'volunteer', 'active'),
    ('jack_bennett', '$2b$12$fryFM3i0n4FqLaJwLoPy8.5avNL1wcXgMtNbKVUcZK6GuNEcC0w0S', 'Jack Bennett', 'jack.bennett@example.com', '021-111-1208', '15 Nikau St, Addington', 'jack_bennett.jpg', 'waste reduction, stream cleanups', 'volunteer', 'active'),
    ('mia_collins', '$2b$12$HF42Bppraig.dC7EPY1LtO65DjlkEmU.PNfQdxwqwb6rNKoaW.9LO', 'Mia Collins', 'mia.collins@example.com', '021-111-1209', '90 Puriri Way, Sydenham', 'mia_collins.jpg', 'beach cleanups, recycling', 'volunteer', 'active'),
    ('leo_mitchell', '$2b$12$4YZfyY6D/7GbwKwgv4R2ZeviFh6kO9aeN97p2lREKMjNy5piRcFem', 'Leo Mitchell', 'leo.mitchell@example.com', '021-111-1210', '33 Kaka Rd, Linwood', 'leo_mitchell.jpg', 'river cleanup, tree planting', 'volunteer', 'active'),
    ('grace_holmes', '$2b$12$qP1CPDFB6ypckwdWs.15leZzalvbeaTXcrARnBMIcITtEVJIGX7sS', 'Grace Holmes', 'grace.holmes@example.com', '021-111-1211', '14 Rimu Close, Riccarton', 'grace_holmes.jpg', 'urban sustainability, composting', 'volunteer', 'active'),
    ('henry_singh', '$2b$12$aYXADp5hnzZ8ADEXZcLmaOH2CVklWQ8cUvAV0ShLJBxhDSqD7UatG', 'Henry Singh', 'henry.singh@example.com', '021-111-1212', '61 Kowhai St, Papanui', 'henry_singh.jpg', 'recycling, public awareness', 'volunteer', 'active'),
    ('ella_jones', '$2b$12$uJ6KHTpWo4pkQ1FNEQmOreP90EShXzYccovenSWCaAwXHwc0gJ6Su', 'Ella Jones', 'ella.jones@example.com', '021-111-1213', '24 Matai Rd, Cashmere', 'ella_jones.jpg', 'wetland cleanup, tree planting', 'volunteer', 'active'),
    ('lucas_webb', '$2b$12$E2TLf7uuiIAKPmNqV0dQXuG2/okGqxIjtHPz6Mkydk2nzRtkXHKt2', 'Lucas Webb', 'lucas.webb@example.com', '021-111-1214', '3 Fantail Grove, Belfast', 'lucas_webb.jpg', 'event volunteering, litter mapping', 'volunteer', 'active'),
    ('chloe_patel', '$2b$12$4/kUvzxfocR40uaQsWRXJuQQfrnuCiWSBV7GGHCkoC7JmNYax1Y/a', 'Chloe Patel', 'chloe.patel@example.com', '021-111-1215', '77 Huia Dr, Rangiora', 'chloe_patel.jpg', 'beach cleanups, youth outreach', 'volunteer', 'active'),
    ('oliver_reid', '$2b$12$rJwxh19pGDDhsoOZIdNi/Ox5aBQmDWT8e0qXO4Ba8E95o91lCP2K.', 'Oliver Reid', 'oliver.reid@example.com', '021-111-1216', '18 Piwakawaka St, Lincoln', 'oliver_reid.jpg', 'river cleanup, biodiversity', 'volunteer', 'active'),
    ('zara_cooper', '$2b$12$ghVAKkcUQpSiiaxFTA7hF.5jFku4jVFhD6WpFYOv5qgPMbVaUVdOa', 'Zara Cooper', 'zara.cooper@example.com', '021-111-1217', '29 Moa Way, Kaiapoi', 'zara_cooper.jpg', 'plastic reduction, reuse', 'volunteer', 'active'),
    ('arthur_lee', '$2b$12$MbHUQraEioPMlI9ifICaH.cNpSti5FpIwJJT8EkZUtYMUVnGs44P2', 'Arthur Lee', 'arthur.lee@example.com', '021-111-1218', '5 Heron Cres, Avonhead', 'arthur_lee.jpg', 'community cleanup, data tracking', 'volunteer', 'active'),
    ('ruby_ross', '$2b$12$S3dRqKr6IMhttsq4Vx88L.Gwoj2//Vs48HgPAeZeLjlrtiC82ZBWu', 'Ruby Ross', 'ruby.ross@example.com', '021-111-1219', '64 Teal St, Prebbleton', 'ruby_ross.jpg', 'recycling, educational campaigns', 'volunteer', 'active'),
    ('mason_kelly', '$2b$12$v2JncEuOHLnhS.8UfiTime3.8mT4qptpB9ko3w.5637gh3dS.Oofy', 'Mason Kelly', 'mason.kelly@example.com', '021-111-1220', '46 Swan Rd, Templeton', 'mason_kelly.jpg', 'tree planting, creek cleanup', 'volunteer', 'active'),
    ('leader_hana', '$2b$12$m40cwJtP1JoGDXx3P8pVDOF6hEFUs2vNWDAkQcFYAF2Wdfm1TAzK.', 'Hana Thompson', 'hana.thompson@example.com', '021-222-3101', '11 Olive St, Lincoln', 'leader_hana.jpg', 'event planning, volunteer coaching', 'event_leader', 'active'),
    ('leader_rory', '$2b$12$D5HwKYWqklQwbkstiX4mvupEfk90.bddCYbJiYdZv55bSiCtez2xy', 'Rory Miles', 'rory.miles@example.com', '021-222-3102', '16 Walnut Ave, Rolleston', 'leader_rory.jpg', 'waste auditing, logistics', 'event_leader', 'active'),
    ('leader_pia', '$2b$12$p0/eOC4kFGELkmPO5iiQHejg8nmdvsw.dU0gy3qyotqrZ.Rm0Hsx.', 'Pia Morgan', 'pia.morgan@example.com', '021-222-3103', '72 Riverbank Rd, Christchurch', 'leader_pia.jpg', 'coastal restoration, safety', 'event_leader', 'active'),
    ('leader_daniel', '$2b$12$T2KfHx6D1GcQFYkmgJ53AuKLumeogyMzbPSHgwD5ZbOvap3JtIU/e', 'Daniel Young', 'daniel.young@example.com', '021-222-3104', '9 Estuary View, New Brighton', 'leader_daniel.jpg', 'event facilitation, outreach', 'event_leader', 'active'),
    ('leader_erin', '$2b$12$ReGU75B7ieOwahI8eOeM1.t6uJ1ZeN.gQa.wlcGGn7/16DVwiHIlC', 'Erin Black', 'erin.black@example.com', '021-222-3105', '55 Summit Rd, Lyttelton', 'leader_erin.jpg', 'wetland projects, reporting', 'event_leader', 'active'),
    ('admin_nora', '$2b$12$7cAAr.3XrITeW1AU1k3MZeGFHf.Ib2eaYjxDpaNQ4qFmVk99abp2O', 'Nora Patel', 'nora.patel@example.com', '021-333-4101', '2 Admin Lane, Christchurch', 'admin_nora.jpg', 'platform administration, governance', 'admin', 'active'),
    ('admin_tom', '$2b$12$IMBmb5WfTWcaH.x3i6e.8OoJ.jq5ovRG.3At3C/Y54bZoWlFMLFbS', 'Tom Hughes', 'tom.hughes@example.com', '021-333-4102', '8 Admin Lane, Christchurch', 'admin_tom.jpg', 'operations, compliance', 'admin', 'active');

INSERT INTO events (
    event_name, event_leader_id, location, event_type, event_date,
    start_time, end_time, duration, description, supplies, safety_instructions
) VALUES
    ('Avon Riverbank Recovery', 21, 'Avon River, Christchurch', 'river cleanup', '2026-01-20', '09:00', '12:00', 180, 'Join us to remove litter and debris along key sections of the Avon Riverbank. We will work in small teams to cover both walking paths and vegetation edges. Volunteers will help sort collected waste so recyclables can be processed correctly.', 'Gloves, bags, tongs', 'Briefing at check-in'),
    ('Spencer Park Sweep', 22, 'Spencer Park Beach', 'beach cleanup', '2026-01-26', '08:30', '11:00', 150, 'This beach cleanup focuses on plastic waste around the high tide line and picnic zones. Volunteers will collect, sort, and record common waste types for community reporting. Families are welcome, and tasks will be matched to different activity levels.', 'Gloves, buckets, sunscreen', 'Wear covered shoes'),
    ('Lincoln Wetland Revive', 23, 'Lincoln Wetland Reserve', 'wetland cleanup', '2026-02-02', '10:00', '12:00', 120, 'Help restore the walking paths and habitat edges at Lincoln Wetland Reserve. We will remove visible litter and protect sensitive zones from further disturbance. A short guidance session will explain how to work safely around wetland plants and birds.', 'Gloves, nets, bins', 'Stay on marked paths'),
    ('Halswell Stream Care', 24, 'Halswell Stream', 'stream cleanup', '2026-02-08', '09:30', '12:30', 180, 'We are cleaning stream banks where dumped waste often builds up after rain. Teams will collect rubbish, separate recyclables, and report larger hazards to the coordinator. This event supports cleaner waterways and healthier local wildlife habitats.', 'Bags, grabbers, first aid kit', 'Avoid steep banks'),
    ('New Brighton Dune Day', 25, 'New Brighton Foreshore', 'coastal cleanup', '2026-02-12', '11:00', '13:00', 120, 'Spend the morning protecting dune ecosystems at New Brighton Foreshore. Volunteers will remove litter, sift for microplastics, and log findings for local awareness work. The event includes a quick talk on why dune vegetation is vital for coastal resilience.', 'Bags, sifters, gloves', 'Hydration required'),
    ('Riccarton Park Litter Blitz', 21, 'Riccarton Bush', 'park cleanup', '2026-02-15', '09:00', '11:30', 150, 'This cleanup targets trails, rest areas, and popular gathering spots in Riccarton Bush. Volunteers will collect litter and separate general waste from recyclable items. Hazardous objects will be flagged for safe handling by the event team.', 'Gloves, tongs, sharps container', 'Report hazardous items'),
    ('Lyttelton Harbour Care', 22, 'Lyttelton Harbour', 'harbour cleanup', '2026-02-22', '08:30', '11:30', 180, 'Join a coordinated cleanup along the harbour edge to reduce marine pollution risks. We will remove shoreline rubbish and sort materials for recycling where possible. Safety leaders will guide all water-adjacent tasks and monitor changing conditions.', 'Bags, gloves, life jackets', 'Water edge safety briefing'),
    ('Bottle Lake Forest Action', 23, 'Bottle Lake Forest', 'forest cleanup', '2026-02-24', '10:00', '12:00', 120, 'Support a cleaner forest environment by clearing litter from key track sections. Small groups will follow mapped routes to ensure broad area coverage. The team will also note hotspots to help improve future prevention and education efforts.', 'Bags, gloves, maps', 'Stay with assigned team'),
    ('Kaiapoi River Edge', 24, 'Kaiapoi River', 'river cleanup', '2026-02-26', '09:00', '12:00', 180, 'This riverside event focuses on debris removal from access points and river margins. Volunteers will collect waste, sort recyclable materials, and record unusual items for reporting. Pair work is encouraged so everyone can move safely near uneven ground.', 'Gloves, ropes, bags', 'No solo work near water'),
    ('Sumner Beach Morning', 25, 'Sumner Beach', 'beach cleanup', '2026-02-28', '08:00', '10:30', 150, 'Start your day with a community cleanup at Sumner Beach. Teams will cover shoreline zones, collect litter, and transfer materials to a sorting station. We will also share quick tips for reducing single use plastic in everyday life.', 'Gloves, buckets, sunscreen', 'Check tide schedule'),
    ('Rangiora Green Corridors', 21, 'Rangiora Domain', 'community cleanup', '2026-03-02', '09:30', '11:30', 120, 'Help tidy green corridors and public paths used by local families and walkers. Volunteers will remove litter, separate recyclables, and keep records of what is most frequently found. This data helps guide future community education campaigns.', 'Bags, gloves, litter pickers', 'Traffic safety near roads'),
    ('Hoon Hay Reserve Restore', 22, 'Hoon Hay Reserve', 'park cleanup', '2026-03-04', '10:00', '12:00', 120, 'Join us to restore reserve spaces by removing litter from grass areas and pathways. Collected items will be sorted into waste and recycling streams onsite. The event is beginner friendly and ideal for volunteers who are new to cleanup activities.', 'Bags, gloves, bins', 'Children must be supervised'),
    ('Estuary Edge Action', 23, 'Avon-Heathcote Estuary', 'estuary cleanup', '2026-03-06', '08:30', '11:30', 180, 'This estuary cleanup supports bird habitat health and cleaner tidal edges. Volunteers will collect rubbish, focus on high impact plastics, and document what is recovered. Team leaders will direct movement through approved access routes to protect sensitive areas.', 'Gloves, bags, waders', 'Use approved access routes'),
    ('Templeton Creek Rescue', 24, 'Templeton Creek', 'stream cleanup', '2026-03-08', '09:00', '11:30', 150, 'Work with local volunteers to remove waste from creek edges and nearby public access points. We will sort materials, track quantities, and flag hazards for follow-up action. Regular team check ins keep the group coordinated and safe throughout the session.', 'Bags, tongs, first aid kit', 'Team check-ins every 30 min'),
    ('Prebbleton Waste Watch', 25, 'Prebbleton Village', 'community cleanup', '2026-03-10', '10:00', '12:00', 120, 'Support a cleaner village center by collecting litter from streets, parks, and shared spaces. Volunteers will sort recyclables onsite and prepare waste for proper disposal. The session includes a short wrap up on practical waste reduction habits for daily life.', 'Bags, gloves, sorting bins', 'Sort recyclables onsite'),
    ('Cashmere Hills Cleanup', 21, 'Cashmere Hills', 'hillside cleanup', '2026-03-12', '09:00', '12:00', 180, 'Help protect hillside trails and lookout points by removing litter along key routes. Teams will move through assigned zones to keep coverage balanced and efficient. Volunteers should expect uneven terrain and follow leader guidance at all times.', 'Bags, gloves, sturdy boots', 'Mind uneven terrain'),
    ('Rolleston Town Centre Sweep', 22, 'Rolleston Town Centre', 'urban cleanup', '2026-03-14', '08:30', '10:30', 120, 'This urban cleanup focuses on public walkways, transport stops, and town center gathering areas. Volunteers will collect litter, separate recyclable materials, and support a cleaner shared environment. The event is short, practical, and suitable for all experience levels.', 'Bags, gloves, hi-vis vests', 'Road crossing safety'),
    ('Waimakariri Riverside Care', 23, 'Waimakariri Riverside', 'river cleanup', '2026-03-16', '09:30', '12:00', 150, 'Join our riverside care day to remove debris and improve local recreation spaces. Teams will collect, sort, and record waste types to support future planning. A safety briefing will cover riverbank risks before work begins.', 'Bags, gloves, grabbers', 'Riverbank hazard briefing'),
    ('Lincoln Campus Green Day', 24, 'Lincoln University Grounds', 'campus cleanup', '2026-03-18', '10:00', '12:00', 120, 'Help keep the campus clean by removing litter from common outdoor areas and pathways. Volunteers will sort waste into clear categories and support visible sustainability action on site. This event is a great option for students who want a short and meaningful contribution.', 'Bags, gloves, bins', 'Follow campus safety rules'),
    ('Pegasus Lake Shore Patrol', 25, 'Pegasus Lake', 'lake cleanup', '2026-03-20', '08:00', '11:00', 180, 'Take part in a lakeshore cleanup focused on plastics and windblown debris. Volunteers will work in pairs to collect litter and count key item types for reporting. Together we can reduce pollution and protect the lake for both wildlife and the community.', 'Gloves, bags, rakes', 'Work in pairs near water'),
    -- Overlapping/same-time event samples for schedule-conflict testing
    ('Avon Morning Microplastics Sweep', 22, 'Avon River, Christchurch', 'river cleanup', '2026-03-12', '09:00', '11:00', 120, 'A focused microplastics sweep along the Avon edge with sorted collection and quick data logging.', 'Gloves, sieve trays, bags', 'Keep distance from river edge'),
    ('Cashmere Track Litter Patrol', 23, 'Cashmere Hills', 'hillside cleanup', '2026-03-12', '10:00', '12:00', 120, 'Patrol and clean upper track sections with hotspot mapping and waste categorisation.', 'Gloves, bags, clipboards', 'Use marked hillside paths only'),
    ('Rolleston Transit Stop Tidy-Up', 24, 'Rolleston Town Centre', 'urban cleanup', '2026-03-14', '08:30', '10:30', 120, 'Clean bus-stop zones and nearby walkways to reduce litter accumulation in commuter areas.', 'Gloves, bags, hi-vis vests', 'Road safety briefing required'),
    ('Pegasus Shoreline Sort Session', 21, 'Pegasus Lake', 'lake cleanup', '2026-03-20', '08:00', '10:00', 120, 'Sort and remove shoreline litter with a focus on recyclable plastics and cans.', 'Gloves, sorting bags, tongs', 'Work in buddy pairs'),
    ('Christchurch City Night Sweep', 24, 'Christchurch CBD', 'urban cleanup', '2026-03-22', '18:00', '20:00', 120, 'Join an evening cleanup around public squares and transport links in the city centre. Teams will focus on fast-moving litter zones and support safer, cleaner shared spaces for commuters and visitors.', 'Gloves, torches, hi-vis vests, bags', 'Stay with your assigned night team'),
    ('Lake Ellesmere Birdsafe Cleanup', 25, 'Te Waihora / Lake Ellesmere', 'estuary cleanup', '2026-03-24', '07:30', '10:30', 180, 'Help remove plastics and line waste from shoreline zones near bird habitats. Volunteers will work in guided lanes to protect nesting areas while collecting and recording debris types.', 'Gloves, sacks, grabbers, field sheets', 'Keep noise low near nesting zones'),
    ('Waipara Trail Reset', 21, 'Waipara Gorge Track', 'trail cleanup', '2026-03-26', '09:00', '12:00', 180, 'Support a trail reset day by clearing litter from viewpoints, rest bays, and side tracks. This event includes hotspot mapping so repeat dump points can be monitored and prevented.', 'Gloves, bags, map tags, first aid kit', 'Use buddy system on uneven track sections'),
    ('University Hostel Recycling Drive', 22, 'Lincoln Student Village', 'recycling drive', '2026-03-28', '14:00', '17:00', 180, 'Work with student volunteers to collect and sort recyclable items across hostel blocks. The session includes clear sorting stations and short coaching on correct recycling practices.', 'Sorting bins, gloves, labels, trolleys', 'Do not lift overloaded boxes'),
    ('Brooklands Lagoon Care', 23, 'Brooklands Lagoon', 'lagoon cleanup', '2026-03-30', '08:30', '11:30', 180, 'Join a lagoon-edge cleanup focused on reducing plastic leakage into tidal channels. Teams will collect, sort, and document common waste categories for local environmental reporting.', 'Waders, gloves, bags, clipboards', 'Follow tidal zone markers and leader calls'),
    ('Redcliffs Coastal Scan', 24, 'Redcliffs Coastline', 'coastal cleanup', '2026-04-01', '07:00', '09:30', 150, 'Take part in an early coastal scan and cleanup to remove overnight windblown waste. Volunteers will split by sector and complete quick waste audits after each collection round.', 'Gloves, collection bags, audit sheets', 'Report sharp objects immediately to leaders');

INSERT INTO eventregistrations (
    event_id, volunteer_id, attendance, registration_status,
    leader_reminder_message, leader_reminder_sent_at, leader_reminder_sent_by
) VALUES
    (1, 1, 'present', 'active', 'Thanks for joining. Please check in by 8:45 AM.', '2026-01-19 18:30', 21),
    (1, 2, 'present', 'active', 'Bring water and covered shoes.', '2026-01-19 18:35', 21),
    (1, 3, 'absent', 'active', 'Let us know early if your plans change.', '2026-01-19 18:40', 21),
    (1, 4, 'present', 'active', NULL, NULL, NULL),
    (2, 4, 'present', 'active', 'Meet at the north carpark sign-in table.', '2026-01-25 17:50', 22),
    (2, 5, 'present', 'active', 'Please bring a reusable bottle.', '2026-01-25 17:55', 22),
    (2, 6, 'absent', 'active', 'Weather update sent in app notice.', '2026-01-25 18:00', 22),
    (2, 7, 'present', 'active', NULL, NULL, NULL),
    (3, 6, 'present', 'active', 'Wetland paths can be slippery. Wear grip shoes.', '2026-02-01 19:10', 23),
    (3, 7, 'present', 'active', NULL, NULL, NULL),
    (3, 8, 'present', 'active', NULL, NULL, NULL),
    (3, 9, 'absent', 'removed', 'Registration removed at volunteer request.', '2026-02-01 20:00', 23),
    (4, 8, 'present', 'active', 'Please arrive 15 minutes early for stream safety briefing.', '2026-02-07 18:45', 24),
    (4, 9, 'absent', 'active', NULL, NULL, NULL),
    (4, 10, 'present', 'active', NULL, NULL, NULL),
    (4, 11, 'present', 'active', NULL, NULL, NULL),
    (5, 10, 'present', 'active', 'Bring sun protection and a hat.', '2026-02-11 19:00', 25),
    (5, 11, 'present', 'active', NULL, NULL, NULL),
    (5, 12, 'present', 'active', NULL, NULL, NULL),
    (5, 13, 'absent', 'active', NULL, NULL, NULL),
    (6, 12, 'present', 'active', 'Sharps bin available at check-in desk.', '2026-02-14 17:40', 21),
    (6, 13, 'present', 'active', NULL, NULL, NULL),
    (6, 14, 'present', 'active', NULL, NULL, NULL),
    (6, 15, 'absent', 'removed', 'Removed due to duplicate signup in another event.', '2026-02-14 17:55', 21),
    (7, 14, 'pending', 'active', 'Reminder: harbour wind can be strong. Bring layers.', '2026-02-21 18:20', 22),
    (7, 15, 'pending', 'active', 'Please complete the safety declaration before arrival.', '2026-02-21 18:25', 22),
    (7, 16, 'pending', 'active', NULL, NULL, NULL),
    (8, 16, 'pending', 'active', 'Meet your team at Track Entrance B.', '2026-02-23 17:30', 23),
    (8, 17, 'pending', 'active', NULL, NULL, NULL),
    (8, 18, 'pending', 'active', NULL, NULL, NULL),
    (9, 18, 'pending', 'active', 'No solo work near river margins.', '2026-02-25 18:05', 24),
    (9, 19, 'pending', 'active', NULL, NULL, NULL),
    (9, 20, 'pending', 'active', NULL, NULL, NULL),
    (10, 20, 'pending', 'active', 'Please check tide update before departure.', '2026-02-27 18:45', 25),
    (10, 1, 'pending', 'active', NULL, NULL, NULL),
    (11, 1, 'pending', 'active', 'We will start exactly at 9:30 AM.', '2026-03-01 18:00', 21),
    (11, 5, 'pending', 'active', NULL, NULL, NULL),
    (11, 9, 'pending', 'active', NULL, NULL, NULL),
    (12, 2, 'pending', 'active', 'Family-friendly event. Bring gloves if you have your own.', '2026-03-03 17:30', 22),
    (12, 6, 'pending', 'active', NULL, NULL, NULL),
    (12, 10, 'pending', 'active', NULL, NULL, NULL),
    (13, 3, 'pending', 'active', 'Please use approved estuary access routes only.', '2026-03-05 18:20', 23),
    (13, 7, 'pending', 'active', NULL, NULL, NULL),
    (13, 11, 'pending', 'active', NULL, NULL, NULL),
    (14, 4, 'pending', 'active', 'Team check-in every 30 minutes at marker point.', '2026-03-07 17:50', 24),
    (14, 8, 'pending', 'active', NULL, NULL, NULL),
    (14, 12, 'pending', 'active', NULL, NULL, NULL),
    (15, 9, 'pending', 'active', 'Bring a reusable cup for warm drinks at wrap-up.', '2026-03-09 18:15', 25),
    (15, 13, 'pending', 'active', NULL, NULL, NULL),
    (16, 10, 'pending', 'active', 'Hillside footwear is required for this event.', '2026-03-11 17:35', 21),
    (16, 14, 'pending', 'active', NULL, NULL, NULL),
    (16, 18, 'pending', 'active', NULL, NULL, NULL),
    (17, 11, 'pending', 'active', 'Hi-vis vest can be borrowed at check-in.', '2026-03-13 18:00', 22),
    (17, 15, 'pending', 'active', NULL, NULL, NULL),
    (18, 12, 'pending', 'active', 'Please pair up before heading to the river edge.', '2026-03-15 18:10', 23),
    (18, 16, 'pending', 'active', NULL, NULL, NULL),
    (19, 13, 'pending', 'active', 'Campus route map will be shared at sign-in.', '2026-03-17 17:20', 24),
    (19, 17, 'pending', 'active', NULL, NULL, NULL),
    (20, 13, 'pending', 'active', 'Arrive early for buddy assignments by the lake.', '2026-03-19 18:15', 25),
    (20, 18, 'pending', 'active', NULL, NULL, NULL),
    (21, 19, 'pending', 'active', 'Microplastics collection uses sieve stations.', '2026-03-11 18:30', 22),
    (21, 2, 'pending', 'active', NULL, NULL, NULL),
    (22, 3, 'pending', 'active', 'Track patrol teams leave every 20 minutes.', '2026-03-11 18:40', 23),
    (22, 6, 'pending', 'active', NULL, NULL, NULL),
    (23, 4, 'pending', 'active', 'Stay clear of active bus bays during cleanup.', '2026-03-13 17:45', 24),
    (23, 7, 'pending', 'active', NULL, NULL, NULL),
    (24, 8, 'pending', 'active', 'Sorting station opens at 7:45 AM.', '2026-03-19 17:55', 21),
    (24, 11, 'pending', 'active', NULL, NULL, NULL),
    (25, 5, 'pending', 'active', 'Night event reminder: bring a head torch if possible.', '2026-03-21 17:40', 24),
    (25, 12, 'pending', 'active', NULL, NULL, NULL),
    (26, 1, 'pending', 'active', 'Sensitive habitat zone. Follow the marked lines.', '2026-03-23 18:00', 25),
    (26, 10, 'pending', 'active', NULL, NULL, NULL),
    (27, 9, 'pending', 'active', 'Buddy system required on all track sections.', '2026-03-25 18:05', 21),
    (27, 20, 'pending', 'active', NULL, NULL, NULL),
    (28, 14, 'pending', 'active', 'Use labelled bins for clean and mixed recyclables.', '2026-03-27 19:15', 22),
    (28, 18, 'pending', 'removed', 'Removed after duplicate booking in event 27.', '2026-03-27 19:20', 22),
    (29, 15, 'pending', 'active', 'Lagoon route can be muddy after rain.', '2026-03-29 18:25', 23),
    (29, 19, 'pending', 'active', NULL, NULL, NULL),
    (30, 16, 'pending', 'active', 'Early start. Please arrive by 6:45 AM for briefing.', '2026-03-31 18:10', 24),
    (30, 17, 'pending', 'active', NULL, NULL, NULL);

INSERT INTO eventoutcomes (
    event_id, num_attendees, bags_collected, recyclables_sorted, other_achievements, recorded_by
) VALUES
    (1, 22, 18, 75, 'High volunteer turnout with strong recyclable recovery.', 21),
    (2, 16, 14, 52, 'Beach plastics reduced significantly near picnic area.', 22),
    (3, 12, 10, 37, 'Wetland paths cleared and sorting station used well.', 23),
    (4, 15, 13, 48, 'Stream edges improved and hazard reports completed.', 24),
    (5, 14, 12, 41, 'Dune zone cleanup completed before noon.', 25),
    (6, 13, 11, 38, 'Park zone covered fully with accurate sorting logs.', 21),
    (7, 18, 16, 58, 'Harbour edge hotspots mapped for the next quarter plan.', 22),
    (8, 11, 9, 29, 'Forest team logged three recurring litter points for signage.', 23),
    (9, 17, 15, 54, 'River access points cleared and large debris flagged to council.', 24),
    (10, 19, 17, 63, 'Morning beach sweep removed high volume of bottles and wrappers.', 25),
    (11, 10, 8, 27, 'Community pathways cleaned with clear waste category reporting.', 21),
    (12, 9, 7, 24, 'Reserve cleanup completed with strong first-time volunteer support.', 22),
    (13, 15, 13, 46, 'Estuary plastics reduced in key bird foraging areas.', 23),
    (14, 12, 10, 35, 'Creek sector teams completed all assigned checkpoints.', 24),
    (15, 8, 6, 21, 'Village zones tidied and recyclables separated accurately.', 25),
    (16, 14, 12, 40, 'Hillside routes cleared and two illegal dumping points reported.', 21),
    (17, 13, 11, 39, 'Town centre litter reduced around bus interchange area.', 22);

INSERT INTO feedback (event_id, volunteer_id, rating, comments) VALUES
    (1, 1, 5, 'Great team coordination and clear safety guidance.'),
    (1, 2, 4, 'Well organised, would like more water stations.'),
    (1, 4, 3, 'Good event overall, but sign-in queue was a bit slow.'),
    (2, 4, 5, 'Beach zone allocation worked really well.'),
    (2, 5, 2, 'The meeting point was hard to find from the parking area.'),
    (3, 6, 4, 'Good event, parking instructions could be clearer.'),
    (3, 7, 5, 'Excellent guidance around sensitive wetland sections.'),
    (4, 8, 5, 'Helpful leader and efficient waste sorting setup.'),
    (4, 10, 3, 'I enjoyed it, but more grabbers would help next time.'),
    (5, 10, 4, 'Enjoyed the cleanup and learning session.'),
    (5, 12, 1, 'I arrived on time but could not see clear check-in signage.'),
    (6, 12, 5, 'Strong community turnout and positive atmosphere.'),
    (6, 14, 4, 'Friendly team and practical waste sorting process.'),
    (7, 14, 5, 'Harbour safety briefing made the whole session feel well managed.'),
    (8, 16, 4, 'Nice pace and clear instructions across trail sections.'),
    (9, 18, 2, 'Would be better with clearer role assignment at the start.'),
    (10, 20, 5, 'Great communication and smooth sorting station flow.'),
    (11, 5, 4, 'Well organised and easy for first-time volunteers to join.'),
    (12, 10, 3, 'Good community spirit, but we ran out of spare gloves early.');


